// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApftwntkrjRbqHRuasvmLyP72TESR6A7k',
    appId: '1:422244375797:web:6191746e94ac9a25ed79bc',
    messagingSenderId: '422244375797',
    projectId: 'fluttercrud-d0a4c',
    authDomain: 'fluttercrud-d0a4c.firebaseapp.com',
    storageBucket: 'fluttercrud-d0a4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCkh1-CZWhhSPvUar1JbZ7bm3HBNoIe2M',
    appId: '1:422244375797:android:9afeb0ec0051baeaed79bc',
    messagingSenderId: '422244375797',
    projectId: 'fluttercrud-d0a4c',
    storageBucket: 'fluttercrud-d0a4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJyB0vIHsLVGzMJ7nJbUSv3yYgiKOARSo',
    appId: '1:422244375797:ios:d29945c71786a200ed79bc',
    messagingSenderId: '422244375797',
    projectId: 'fluttercrud-d0a4c',
    storageBucket: 'fluttercrud-d0a4c.appspot.com',
    iosClientId: '422244375797-jnv8906sn41v72dlrrngbp1p3kpkfseg.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJyB0vIHsLVGzMJ7nJbUSv3yYgiKOARSo',
    appId: '1:422244375797:ios:9509389548717802ed79bc',
    messagingSenderId: '422244375797',
    projectId: 'fluttercrud-d0a4c',
    storageBucket: 'fluttercrud-d0a4c.appspot.com',
    iosClientId: '422244375797-5lriumda64ddmu3tmhd728es5oes7tt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutter.RunnerTests',
  );
}
